### ISSUE TITLE
1.3.(312) GATT sync not successful if user leaves chart view

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station.ios#1035]
Description:

User is GATT syncing multiple local sensors.
If he stays on charts page during sync he will get full data downloaded.
If he moves to sensor card or moves to view another sensor card during sync it will not download full data.

Expected:
GATT sync should always complete downloading sensor data even when user is on another sensor card or view.

https://user-images.githubusercontent.com/50437378/181731464-41695b61-9f01-4873-93d7-fe10d9b972a2.mov

**Comment by priyonto** [comment]
@markoaamunkajo 
This was intentional since the iOS app doesn't support concurrent GATT sync; the sync currently gets canceled when the user leaves the sync state. 
This is to prevent unexpected user experiences if a leaves a syncing page and moves to another card and tries to sync that card. 

I can think of a few more ways to handle it at this moment: 
1. Keep the background syncing for the tag, but if the user tries to sync another tag, we can show a message that concurrent sync is impossible. 
2. Hide the sync button on other tags if a card is already in syncing state. 
3. Show a confirmation alert if the user wants to leave the sync page while syncing that the sync will be terminated if they leave. 

Considering the complexities of implementation, I would prefer to go for the third option. Please share your thoughts. Thanks

**Comment by markoaamunkajo** [comment]
@priyonto yes I think 3 sounds most logical to me.

**Comment by priyonto** [comment]
@markoaamunkajo  Thanks. Would you be able to suggest the message for the alert, please? Thank you.

**Comment by priyonto** [comment]
The alert is implemented. However, the sync cancellation experience is not yet very smooth. It's highly recommended to wait until a sync is completed. Because once the sync is canceled before completion, it takes about 1 minute or so for the tag to return to normal BT state to read measurements or heartbeats. A separate card (#1053) is created for that issue.

**Comment by markoaamunkajo** [comment]
QA passed

**Comment by markoaamunkajo** [comment]
Asked Elias about SE string because build release is near
