### ISSUE TITLE
export headings RSSI & Acceleration need quotes (312)

### ISSUE THREAD

**Issue by DG12** [ruuvi/com.ruuvi.station.ios#1038]
"Date","Temperature (°F)","Humidity (%)","Pressure (inHg)",**RSSI** (dBm),**Acceleration X** (g),**Acceleration** Y (g),**Acceleration Z** (g),"Voltage (V)","Movement Counter" (movements),"Measurement Sequence Number","TX Power" (dBm)

**Comment by markoaamunkajo** [comment]
@priyonto actually let's not use quotes at all because we don't use them anywhere else. This is only shown when opening csv file with simple editor.

<img width="1490" alt="Screenshot 2022-11-17 at 10 13 40" src="https://user-images.githubusercontent.com/50437378/202346169-166e1d06-2b3c-48ee-be75-c02e26918791.png">

**Comment by markoaamunkajo** [comment]
1.3.1(322) @priyonto I see one more quotes in timestamp that should be removed

![csv__timestamp](https://user-images.githubusercontent.com/50437378/203536670-ce853a09-55cf-44b6-8cbd-7acc97338dfa.jpg)

**Comment by DG12** [comment]
For LIbreOffice confusion see issue  #1156

**Comment by DG12** [comment]
The libra office confusion may in fact be due to the "separator options" including space.

I retract my Nov 24 comment. ;-o

**Comment by markoaamunkajo** [comment]
QA passed
