### ISSUE TITLE
Improve claiming process to make it easier

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station.ios#1254]
Description:

Improve claiming process to make it easier

When user adds new sensor with Bluetooth that doesn't yet have owner in Ruuvi Cloud, show this popup first time when user is forwarded to Sensor settings page after adding sensor

No - close popup
Yes - forward user to Claim Sensor page

![Image](https://github.com/ruuvi/com.ruuvi.station/assets/50437378/3ebbbe43-ba34-4618-b648-9de28dff1a4c)

Android card: https://github.com/ruuvi/com.ruuvi.station/issues/921

**Comment by markoaamunkajo** [comment]
QA passed

**Comment by markoaamunkajo** [comment]
@priyonto for some reason this doesn't trigger now when adding new sensor with NFC or manually from Add a new sensor page.
Testing build 393 from Testflight (internal)

**Comment by priyonto** [comment]
@markoaamunkajo I can't reproduce it. However, one note: This may take a few seconds to show, its not instant as soon as you add a sensor. Because, we make a network calls to check if the sensor is claimed by someone else, and then show claim popup. And the network call is made after a sensor is added, so its expected to take some time based on network condition.

**Comment by markoaamunkajo** [comment]
Looks like popup is ok on the latest build. There are other issues, discussing in dm.
