### ISSUE TITLE
Station should not attempt sync if RSSI is null

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station.ios#1367]
Description:

Don’t attempt to sync if RSSI is null

------------------------------------------
Device: iPhone XS Max
OS: iOS 16.3.1
App: Ruuvi Station 2.0.1(358)

Location: not determined
Photo Library: authorized
Camera: authorized
Notifications: authorized

**Comment by markoaamunkajo** [comment]
Hi @DG12 I have new Bluetooth sensor and added it to Cloud account, then activated cloud mode to make RSSI reading to "-". But I am still able to sync local sensor data with Bt sync without issues.

Is this what happened to you?

**Comment by DG12** [comment]
Not related to gateway/cloud.

Ruuvi sensor (22AB) was in range. Move iPhone farther away. Now is out of range. RSSI reported as '-'

User taps Sync.
Station should report 'Sensor out of range' rather than attempting to connect.

Please edit title to be "Station should not attempt sync if RSSI is null  2.0.1(359)" 

Sorry for he delay, we were out now country.

**Comment by DG12** [comment]
### "User should confirm sync if RSSI is too low. 2.0.1(359)"
Would be a much better title in view of issue #1377.
"too low" might be -90 (?)
For example:
"The sensor is at the edge of the radio's range (-90) and
 the synchronization is unlikely to succeed.
Continue anyway?"

**Comment by markoaamunkajo** [comment]
Moving to backlog not urgent, but a good UX improvement

**Comment by markoaamunkajo** [comment]
This seems like an unnecessary improvement, considering that even different phones report BT values differently. Closing for now.
