### ISSUE TITLE
Tags not seen since app startup blanks values and cannot be removed - error  0.6.1(18)

### ISSUE THREAD

**Issue by DG12** [ruuvi/com.ruuvi.station.ios#141]
If data has not been received for an extended period of time the last data should be displayed and
the configuration button should not  be disabled which prevents renaming or removal.

**Comment by rinat-enikeev** [comment]
@DG12 what do you mean by "can't be removed"? Any steps?

**Comment by DG12** [comment]
I have a tag whose trailing 4 digits of MAC is D18B
![RuuviTagD18BNoDetails](https://user-images.githubusercontent.com/2365961/99211459-5a63ce00-2796-11eb-9556-f53592e02e55.jpeg)
.
There is no data currently presented by Ruuvistation IOS
Clicking on the gear in the upper right does no respond so the button to remove the tag that would be on the bottom of the details age cannot be tapped.

**Comment by DG12** [comment]
I revised this title since I now have 3 tags configured which are out of range.
They cannot be renamed or removed since tapping on the gear does not open the details page.

**Comment by rinat-enikeev** [comment]
@DG12 I tried the following steps: 

1. Use tag with 2.5.9 firmware (not connectable as on screenshot)
2. Disable save advertisements in Foreground settings. 
3. Add tag
4. Power off the tag

Expected behaviour: I still can remove the tag
Actual behaviour: I still can remove the tag

So - I wasn't able to reproduce. Any hint for the steps?

**Comment by markoaamunkajo** [comment]
Waiting comment from @DG12

**Comment by DG12** [comment]
Appears to be fix in 0.7(21)

Thanks for not closing my issue.
