### ISSUE TITLE
Charts looking weird for Bluetooth sensor in Cloud mode

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station.ios#1435]
Description:

@priyonto

Tested with this one by adding a Bluetooth sensor when in Cloud mode and phone in airplane mode

I added calibration setting
The updated counter went crazy
And then I'm clearing the local history
Chart looks weird

https://drive.google.com/file/d/1r2JH-q5Zt78nWqE_28AwgvI-2vAz2fG2/view?usp=share_link

**Comment by priyonto** [comment]
The chart looks weird is a separate issue than the other two you mentioned.

1. The counter goes crazy because of this - https://github.com/ruuvi/com.ruuvi.station.ios/issues/1121
2. If you abort a sync it doesn't immediately return to normal state and start advertising - https://github.com/ruuvi/com.ruuvi.station.ios/issues/1053

**Comment by markoaamunkajo** [comment]
QA passed
