### ISSUE TITLE
SQL error report from user

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station.ios#1541]
Description:

Received another SQL error from user through App Store Connect

_Adding an existing sensor results in an SQLite error pop up. Maybe check if the device already exists? Bonus points for showing an icon in the add screen for existing sensors._

He fixed this issue by reinstalling app. But this seems to be reoccurring from time to time.

Reference card:
https://github.com/ruuvi/com.ruuvi.station.ios/issues/738

Notice that this can be reproduced with latest firmware version.

App Version
2.2.0 (386)
Device
iPhone 14 Pro
Version
iOS 16.5.1

![sqlerror](https://github.com/ruuvi/com.ruuvi.station.ios/assets/50437378/69b9dd69-41d9-42a8-b20f-994cc7b9a395)

**Comment by priyonto** [comment]
@markoaamunkajo We have revisited it several times and the best solution is to clean install the app. This may occur if user updated the app from the buggy versions (probably < 1.0.0) to the latest one. The reason is this bug affected the DB and it doesn't go away without uninstalling the app. 

But, if we can reproduce it after clean installing the latest versions... only then its worth spending time in my opinion. Please suggest.
