### ISSUE TITLE
Share error but no error report

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station.ios#1561]
Description:

Share with xx
reports ….  Successfully Shared with xx .

Shortly thereafter xx disappears without mention of error.

**Comment by markoaamunkajo** [comment]
Reproduced. @priyonto the list doesn't update third sharee email to the visible list even the share was success.

**Comment by markoaamunkajo** [comment]
I cannot reproduce it now with latest Testflight or AppStore version

**Comment by markoaamunkajo** [comment]
@priyonto Reproduced. Sorry for long video but you will see the glitch in the end.
Build 2.3.0(391)

**Comment by priyonto** [comment]
@markoaamunkajo Found the issue. If you share a sensor with with an email address which doesn't have an account created already, then this appearing and disappearing happens. Because -

We update the list on the app when share endpoint returns success regardless the sharee has already account with us or just invited. BUT, until the sharee creates an account, cloud doesn't add the new sharee email under "shared" section of the sensor. And, that's why on next cloud sync of the app, the share list updates and removes that email address.

I checked the web station, and new email is not added to the list if the email doesn't have an account with us yet, we just show a success message. 

On the app side, we can probably do the same (not updating the list) and show a different message instead like - The share list will be updated once the sharee creates a Ruuvi Cloud account or such.

**Comment by DG12** [comment]
Successfully sending the email is not an indication of successful sharing **if the sharee does not have an account.**

In this case perhaps "Offered" or "Email sent" or "waiting for response" would be better since no sharing occurs until the sharee logs in and creates an account

**Comment by markoaamunkajo** [comment]
I think moving this to spec

**Comment by markoaamunkajo** [comment]
Closing this card, will be improved on cloud side
