### ISSUE TITLE
Gateway / data forwarding feature

### ISSUE THREAD

**Issue by pslestang** [ruuvi/com.ruuvi.station.ios#1630]
Hello,

Do you plan to implement data forwarding feature in iOS as you already did in Android mobile app?

Thank you!

**Comment by laurijamsa** [comment]
We haven't put it on our todo list because iOS cannot scan nearby broadcasting Ruuvi sensors when the app is not on foreground without establishing connections with those. But this could actually work with connected sensors. Let's keep this issue open as a proposal and we will discuss internally if we should take a better look at this.

**Comment by markoaamunkajo** [comment]
Closing this issue, we decided to only support this in Android because iOS cannot do background scanning reliably. We haven't received enough requests to support this feature on iOS.
