### ISSUE TITLE
2.6.1 sensor showing wrong updated time

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station.ios#1955]
Description:

Currently stopped rollout because of Bluetooth sensor cards showing wrong updated time. None of the cloud sensor cards are affected.

Issue is showing within few minutes of adding few 3.32.1 longlife sensor cards to the app.
It seems it's not limited to it though. Also saw it on regular 3.31.1 sensor card after running app all night and checking this morning. In my setup I also have a longlife card and cloud sensor cards.

Sensor cards that have been paired and using heartbeat don't seem to be easily affected by this, but I need longer tests to verify.

**Comment by rinat-enikeev** [comment]
So the reliable steps to reproduce: 

1. flash longlife firmware on the tag `A`
2. add tag `A` and any tag `B` to the newly installed Ruuvi Station
3. press reset on tag `A`

Expected: 
only recent values are shown 

Actual: 
blinks of old values on cards


fixed in https://github.com/ruuvi/com.ruuvi.station.ios/pull/1960

**Comment by markoaamunkajo** [comment]
QA passed
