### ISSUE TITLE
0.7(21) Network sensor is showing "Connected" status on card

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station.ios#197]
Description:

User is logged to network and only has network cards in Ruuvi Station
(He added one normal tag, connected it and then deleted card)
Now network cards are showing status "Connected"

This is unnecessary for network cards

**Comment by markoaamunkajo** [comment]
Hi, I'm confused with this popup... Is it supposed for some reason to be able to "keep connection"? I'm expecting that network would have priority and connected option would not be displayed if sensor data was collected from network. Same should happen if tag was assigned as network sensor.


https://user-images.githubusercontent.com/50437378/115483128-62aac280-a27a-11eb-97ca-6f9cf7c62207.mov

**Comment by rinat-enikeev** [comment]
> 0.7(22) Hi, I'm confused with this popup... Is it supposed for some reason to be able to "keep connection"? I'm expecting that network would have priority and connected option would not be displayed if sensor data was collected from network. Same should happen if tag was assigned as network sensor.
> Also: remove the keep connection switch from sensor settings if sensor is assigned to network

It's already done. If you never heard via Bluetooth from the sensor, it's UUID is nil and the dialog is not shown. Also keep connection toggle is hidden. 

But, if you received data via Bluetooth, it is expected to see the dialog and switch on settings. 


In order to check, please remove battery from specific sensor, fresh install the app and login to network. You'll ensure all the cases work :)

**Comment by markoaamunkajo** [comment]
Indeed it works. QA passed
