### ISSUE TITLE
Follow selected resolution in all chart settings

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station.ios#1996]
Description:

Let's improve this so that calculation is always done with precise values for Min/Max/Avg
Make sure that Last datapoint and Selected datapoint conversion uses high resolution values as well

Show in UI resolution that user has selected in settings everywhere in the app including Min/Max/Avg

![Image](https://github.com/ruuvi/com.ruuvi.station.ios/assets/50437378/c1801511-4926-43e8-a618-02cdd284317d)

Android card: https://github.com/ruuvi/com.ruuvi.station/issues/1230

**Comment by andreevdenis** [comment]
Discussed during meeting to apply user selected resolution to min/max/avg/latest. Selected point should still show full resolution anyway.

**Comment by rinat-enikeev** [comment]
What build is it? Atm latest shows in correct resolution for me. 



<img src="https://github.com/ruuvi/com.ruuvi.station.ios/assets/722716/7ac94d17-890e-4721-9f0a-188a2e74a19f" width=480/>

**Comment by laurijamsa** [comment]
I see some possible confusion here.

The screenshot has probably latest value 29.00C that is represented in 29C instead of 29.00C even if user has selected .01 as resolution setting. This should be unified with Android and webUI to show 29.00C and not 29C.

But another thing is that we have decided to show "min/max/average" values according to the user's resolution settings. But the value that is showed in the box when user taps on the graph should always show full .01 resolution. Compare with webUI, it has been already tested to work like this.

**Comment by markoaamunkajo** [comment]
QA passed
