### ISSUE TITLE
0.6.2(5) CSV export doesn't include all data

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station.ios#210]
Description:

User exported tag data to csv and while data was available they were not included in csv file

Acceleration
Voltage
Movement Counter
Measurement Sequence
TX power

![Screenshot 2021-02-09 at 21 04 21](https://user-images.githubusercontent.com/50437378/107374904-b41c3000-6b1a-11eb-8465-0c9543d28afe.png)

**Comment by DG12** [comment]
See also https://github.com/ruuvi/ruuvi.firmware.c/issues/99

**Comment by viikufa** [comment]
<img width="1197" alt="image" src="https://user-images.githubusercontent.com/13885861/108111339-5e193080-70b6-11eb-8ef0-ebddb5f64945.png">

As I see, we get these measurements only if the sensor is connected. The data from the sensor's log does not contain these fields. 

Link to model of the log item in BTKit
https://github.com/rinat-enikeev/BTKit/blob/9d7594518db694326858809e592dfc971bb16991/Sources/BTKit/Devices/BTServices.swift#L567

**Comment by rinat-enikeev** [comment]
@markoaamunkajo, these logs are from the tag internal storage. As Otso said in https://github.com/ruuvi/ruuvi.firmware.c/issues/99 - we are not going to support storing: 

Acceleration
Voltage
Movement Counter
Measurement Sequence
TX power

I the near future. 

So this issue can be closed. 

PS: if you are wondering why some rows have data - this is because they source is not on_the_tag logs, but heartbeats.

**Comment by markoaamunkajo** [comment]
Ok moving to done because unable to support.
