### ISSUE TITLE
Badge counter issues

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station.ios#2131]
Description:

Looks like there are some issues with badge counter probably related to notification logic itself.

When I see the notification when app is in the foreground (Bluetooth) it is considered "seen" so when I have second notification coming in it will show "1" even though I have 2 uncleared notifications. Limit alert notifications is on.

https://github.com/user-attachments/assets/b35a9984-8ddb-4848-ade0-8c78ff2470dc

**Comment by priyonto** [comment]
This is expected behaviour. When you open the app by tapping the app icon it is expected to clear all the badge. So your `1` became `0`, badge is gone. Then you got another notification which is indicated by the badge `1`. However, opening the app only clears the badge but doesn't clear the delivered notifications, they are cleared only if you tap on them or clear manually. Therefore, I making making the change now that will clear the delivered notifications as well from notification center once you open the app.

**Comment by markoaamunkajo** [comment]
QA passed
