### ISSUE TITLE
Improve migration experience

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station.ios#2186]
Description:

User feedback, no screenshots. Looks like sign out did not happen properly for some reason for this user.

HI, migration of ruuvi app did not go smoothly when setting up new ipad from backup: 

- Sign in was left in weird state. App indicated I was signed in but it was showing blank where my email address should have been and no sensors were visible. 
- When I pressed “sign out” a warning was displayed and I did not do this, instead I deleted the app and reinstalled - no problem with this and everything is working now so this is just a suggestion for future improvement.

Migration issues are rare and low priority, keeping this in backlog for now. Solution for users at this point is to reinstall app.

**Comment by laurijamsa** [comment]
How can we know that they are rare? I would approximate that every day averagely even more than ten of our iOS users switch to a new iOS device and if migration is still broken (we tried to fix it last year iirc), we should fix it again in near future.

**Comment by priyonto** [comment]
Proper solution for this would be sign out user when they restore from backup.

**Comment by priyonto** [comment]
@laurijamsa @markoaamunkajo I have done testing by backing up device to iCloud and restore it twice, I did not face the issue reported by the user. I see I am signed in fine and getting the data from cloud as expected. However, I have done some improvements in the code which may or may not caused this and I am expecting it will work as expected. Additionally, as mentioned above we could sign out users automatically when they restore from backup, should we do it? Its not very intuitive but it will probably prevent bugs like reported ones. Do we want to do it? 
My personal opinion is No, because I think its not intuitive, and if we can keep users signed in, we should try to continue to do that.

**Comment by laurijamsa** [comment]
We can keep users signed in after restoring the app from backups to a new device IF it finally works now. So we need to be able to test it in real life before making the decision.

**Comment by markoaamunkajo** [comment]
Sad news, I cannot test this in a real way by migrating to second device due to this issue.
![Image](https://github.com/user-attachments/assets/d76424d7-8523-4987-84a1-170ca7bbe2db)

**Comment by priyonto** [comment]
@markoaamunkajo You can probably download the app from firebase without REMOVING this app after restoring. That should give you same experience of downloading from AppStore.

**Comment by markoaamunkajo** [comment]
Finally tested this and when I open Ruuvi Station I am not signed in and no errors were shown. This is QA passed.
