### ISSUE TITLE
Unification: Add Chart settings to iOS

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station.ios#489]
Description:

Please add Chart Settings, same as Android
Remove iOS Advanced Settings/Charts

Check what is the downsampling interval on Android when disabling Display all data in chart

**Comment by markoaamunkajo** [comment]
0.7.7(248)
User has one cloud sensor, sets viewport size to 2 days, then disables "Display all data in chart"
Comparing with Android version with same settings something is off with iOS build. The selected unit is inHg for airpressure.

![IMG_2851](https://user-images.githubusercontent.com/50437378/154664260-a239613d-8dec-4740-a17e-9280e17da4ca.JPG)

**Comment by priyonto** [comment]
> Comparing with Android version with same settings something is off with iOS build. The selected unit is inHg for airpressure.
I have created a separate issue  (#754) for the above-mentioned problem since that requires more time and attention. I believe the data storing algorithm on iOS is not similar to android. I will investigate this and rectify that. 

But, I am moving this card to the QA queue /In review to keep it separate and only focus on tag settings functionalities. @markoaamunkajo

**Comment by markoaamunkajo** [comment]
OK settings part is QA passed, moving this card to done
