### ISSUE TITLE
Info popup for Keep Connection

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station.ios#492]
Description:

Add info popup for Keep Connection setting in Sensor Settings

This setting enables alerts for this sensor and allows collecting data from sensor locally while app is running in background.

Replace this same text to popup shown on Charts when user opens first time.

**Comment by laurijamsa** [comment]
> Replace this same text to popup shown on Charts when user opens first time.

This same string you're suggesting cannot be really used instead of the current popup string when user opens the charts first time because they are so different: https://github.com/ruuvi/station.localization/blob/ac50ce7923f82843bd9fa181f054720b4bcffc53/station.localization.json#L213

"This setting enables Bluetooth alerts for this sensor and allows collecting data from sensor locally while app is running in background." in Finnish is: "Tämä asetus mahdollistaa Bluetooth-hälytykset ja historiatietojen tallentamisen sovelluksen omaan muistiin silloinkin, kun sovellus on taka-alalla."

**Comment by markoaamunkajo** [comment]
QA passed

**Comment by markoaamunkajo** [comment]
0.7.7(250) Isn't supposed to be shown if sensor fw is 2.5.9 (it is not connectable)

**Comment by markoaamunkajo** [comment]
QA passed
