### ISSUE TITLE
Auto organise sensors alphabetically according sensor names (quick and allows user to reorganise by renaming)

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station.ios#583]
Description:

Auto organise sensors in app alphabetically
Remember to sort also names with scandinavian letters.

Android card: https://github.com/ruuvi/com.ruuvi.station/issues/472 already implemented

**Comment by priyonto** [comment]
In the CardPresenter.swift file on line 365 adding this piece of sorting code should provide the expected behavior. It sorts the tags by their names alphabetically. 

<img width="825" alt="583_solution" src="https://user-images.githubusercontent.com/24395776/148785181-61bf65f0-2ab2-41e8-95eb-9626efcce0d2.png">

**Comment by markoaamunkajo** [comment]
QA passed
