### ISSUE TITLE
Unification: Show Y-axis values only on the left side of a graph like on Android

### ISSUE THREAD

**Issue by laurijamsa** [ruuvi/com.ruuvi.station.ios#591]
Also, make sure that numbers can fit there.

![image](https://user-images.githubusercontent.com/1311912/134036093-d7482f0b-65cd-46d6-9ff5-0746867d04c8.png)

**Comment by markoaamunkajo** [comment]
0.7.7(248) iPhone 7 @priyonto 
Can chart be aligned so that the date doesn't cut on the right hand side?

![IMG_8197](https://user-images.githubusercontent.com/50437378/154622039-7f73c6b0-ce2c-4702-bfb7-e992f372d46a.PNG)
![IMG_8196](https://user-images.githubusercontent.com/50437378/154622049-346a6a4d-29a5-434c-a1ae-f3e882845a82.PNG)

**Comment by markoaamunkajo** [comment]
QA passed
