### ISSUE TITLE
Try to add a sensor which is already added it gives you a nice SQL error about it

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station.ios#603]
Hi,

There are a few issues with the iOS app:
- If you try to add a sensor which is already added, it gives you a nice SQL error about it. Maybe it could be smart enough to not even offer you the opportunity to add it again (without deleting it first).
- The link in the navigation to contact you does not work and gives an error message (so I had to write feedback via email)
- I had a situation today where my sensors were on, and transmitting but the app did not pick it up. I tried restarting the phone, bluetooth etc. but nothing worked. When I removed the sensor and added it again, it worked.

BR,
Dean

**Comment by markoaamunkajo** [comment]
First mentioned is kind of a known issue due to unfinished cloud sync implementation.
https://github.com/ruuvi/com.ruuvi.station.ios/issues/604

**Comment by markoaamunkajo** [comment]
Asked customer for more info.

**Comment by markoaamunkajo** [comment]
I have an iPhone 13 Pro, running latest iOS 15.1 and ruuvi app version 0.7.6 (206).

I am using my tags only with my phone. I am certain I was in range of the tags when I had this issue because I physically removed it from sauna, opened it up to check the LED was flashing. As mentioned, the only way to get updates was to remove the sensor and add it again (as it appeared in the list of available sensors to add).

BR,
Dean

**Comment by laurijamsa** [comment]
@markoaamunkajo should this issue stay in review or shall we move to Urgent Todo?

**Comment by markoaamunkajo** [comment]
Moving to Urgent Todo, but I have not been able to reproduce this issue.

**Comment by priyonto** [comment]
@markoaamunkajo , Thank you for detailed report. I have some interesting findings on the current dev build 0.7.7(244) in contrast to the issues mentioned here. 

1. In my testing if a sensor is added already from the device, I can't see it anymore in the add sensor screen. You have mentioned that as a possible solution as well. On the other hand, If a sensor is added to the android app locally, I can see the same sensor connectable to the iOS app. And, I can add that sensor without any problem on the iOS app. 

2. I was able to reproduce this issue. This link actually opens up an email drafting page with  IF the user is logged in to default "Mail" app on the iPhone, like the image attached below. However, if user is not logged in to the "Mail" app that shows an error. What we can do here is to open the default email app instead when that link is clicked since iOS 14 supports the default mail app now. 
![IMG_5053](https://user-images.githubusercontent.com/24395776/151346844-9f541ef7-9a18-4a9e-9878-3f3b0511abd1.PNG)

3. I am not sure whether we have this issue anymore in the recent builds. 

Tested on: iPhone 11 Pro Max, iOS 15.2.1

Please share your insight on these issues. Thank you.

**Comment by markoaamunkajo** [comment]
@priyonto 
1. This info is from user. I believe he is talking about trying to add local sensor to same device where it already exists. However I haven't been able to replicate this issue.

2. Oh so feedback button opening Mail app when user has not configured it will give error? In this case what you suggested makes sense.

**Comment by priyonto** [comment]
@markoaamunkajo 

Thank you for your feedback. If 1 and 3 are not reproducible I believe we can fix the number 2 and move on.
