### ISSUE TITLE
0.7.6(223) App crash after signout from cloud

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station.ios#642]
Description:

iPhone 7, iOS 14.8, fresh installation

User signs into Ruuvi cloud and sensors are synced to Ruuvi Station. User then decides to sign out and after confirmation all sensor cards are removed successfully. But then he changes his mind again and minimises the add sensor page and taps on the empty screen space

Actual:
App crashes without submit error popup

Expected:
Let user continue and go to menu

Additional notes:
See how user continues to sign in after crash and the cards are not synced to phone until he kills app. Something weird going on.

https://user-images.githubusercontent.com/50437378/146010371-d3ab42cc-a5b5-464f-a2cc-fdf5e88dfa88.mov

**Comment by markoaamunkajo** [comment]
Same crash on iPhone 6 Plus iOS 15.2

**Comment by priyonto** [comment]
Reason: When user logs out the local storage is being cleared and when they log back in touch the homepage, when there are no sensors added that triggers this method. The scrollView want's to move based on touch but due to the fact that there are no sensors added at that moment the scrollView can not scroll to that page. A simple check on the item count before the scroll action should solve the crash.  

<img width="760" alt="652_solution" src="https://user-images.githubusercontent.com/24395776/148782920-76b92921-19a0-41f8-af60-0f61624d184f.png">

**Comment by andreevdenis** [comment]
Local storage should be cleared only from cloud sensors so it's possible that few sensors left after logging out but currentPage > viewModels.count. Keep this in mind.

**Comment by priyonto** [comment]
I believe so that it's possible that few sensors left after logging out. But, Putting this check prevents the scrollView to scroll if there are no items on the viewModels, which is the logical thing to do I believe.

**Comment by andreevdenis** [comment]
I'm not 100% sure because I don't know Swyft, but maybe it's possible that only 2 sensors left but app is triying to scroll to page 5. If it's not possible then ignore my comment.

**Comment by priyonto** [comment]
currentPage is the index to inform scrollView which page to load. In each scroll,  currentPage is updated. So there's no way to scroll to page 5 if you have only 2 items in the viewModels. But, the problem currently happening is when uses out the viewModels count are 0, and the current page is also 0. Now, if you try to scroll to index 0, that's going to crash the app because there are no items in index 0. That's why we need to put this check. I hope this clears the confusion.

**Comment by andreevdenis** [comment]
Yeah, it should work this way.

**Comment by markoaamunkajo** [comment]
QA passed
