### ISSUE TITLE
sensor last updated by gateway 54 days ago shown but no values

### ISSUE THREAD

**Issue by DG12** [ruuvi/com.ruuvi.station.ios#654]
Ruuvi EFEB correctly shows MAC address of F8:C5:5B:6C:EF:EB and owner but no other data and no icon for last update source.
Android shows last readings including last update of 10/30/21 13:00 by gateway.

**Comment by laurijamsa** [comment]
The mobile apps store locally only 10 days of data but maybe Android stores the latest datapoint additionally in some cache and for this reason the 54 days old datapoint is shown on Android but not on iOS. @andreevdenis could you please confirm if this is the case? And is it so that iOS shows no data at all if latest datapoint is over 10 days old? Caching the latest point somewhere else makes sense to me because it gives a better user experience.

**Comment by andreevdenis** [comment]
For optimisation purposes we got 2 separate tables to store values:
 - one latest measurement for each sensor (we show it in the website card or in sensor settings)
- 10 days history (for charts)


So even if the history table is empty for a specific sensor we still will have the latest measurement in another table.

**Comment by markoaamunkajo** [comment]
@laurijamsa @andreevdenis 
We decided to do do the following on iOS app for UX simplicity in mind:

Currently after 10 days sensor history is empty and showing "-"
Since it's difficult to implement a separate table on iOS to show last old datapoint we will additionally show something like "No data in last 10 days" instead of running date/hour at bottom right corner.

It's also that we don't want to make user confused showing old and irrelevant data.

**Comment by markoaamunkajo** [comment]
QA passed
