### ISSUE TITLE
Share sensor text obscures (Send) - minor 0.7.7(247)

### ISSUE THREAD

**Issue by DG12** [ruuvi/com.ruuvi.station.ios#732]
After tapping on [Type email], the keyboard slides up and hides the (Send) button.
Pressing [return] does not complete the entry.

The text "You can share the sensor...
Seems to have excessive space between the lines. 

Although sliding up will  expose the (send) button it not very friendly or intuitive.
![ShareWhereIsSendButton](https://user-images.githubusercontent.com/2365961/153517711-4df36275-ddc6-4522-a663-d376c91d3fcf.PNG)

**Comment by laurijamsa** [comment]
I experienced this too and it's not a good user experience. Let's make the view to scroll when keyboard is open and button is not visible OR make the return button to trigger the sharing.

**Comment by priyonto** [comment]
> I experienced this too and it's not a good user experience. Let's make the view to scroll when keyboard is open and button is not visible OR make the return button to trigger the sharing.

Yes, I agree. This is not good user experience.

**Comment by priyonto** [comment]
I think we should retain the send button as it is and execute the share action on return could raise cases where the user accidentally tapped return and did not mean to share just yet. 

https://user-images.githubusercontent.com/24395776/162236449-3a3513ee-49a7-466b-96b9-b0d9733719d2.MP4

This is the approach I suggest - 
When the keyboard is open the screen will be scrolled to the bottom so that all contents of that screen are visible including the share button. And, when return is tapped the keyboard will be closed only. And, tapping share will execute the request.

**Comment by DG12** [comment]
Looks good now.
