### ISSUE TITLE
0.7.7(248) Chart doesn't draw points to new sensor

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station.ios#744]
Description:

IPhone 7, iOS 14.8
3.31.1 firmware
Connected mode

User adds new sensor to Ruuvi Station and sets it to Connected mode
Keeps app in foreground, on Charts view
No datapoints are drawn to charts in 30 minutes time

Expected: advertisements/heartbeats should be recorded and chart drawn

![IMG_8200](https://user-images.githubusercontent.com/50437378/154626920-2150cf3d-3405-43b2-91f0-6b287b63a7d2.PNG)
![IMG_8199](https://user-images.githubusercontent.com/50437378/154626941-ea253e7c-32d0-4a37-ab93-f15abba3864a.PNG)

Edit: now I see first datapoint between 12.22 - 12.58

**Comment by markoaamunkajo** [comment]
0.7.7(249) Now I see first datapoint in chart within 3 minutes but there are already multiple points in csv

[Ruuvi 319E_20220303-1025.csv](https://github.com/ruuvi/com.ruuvi.station.ios/files/8174735/Ruuvi.319E_20220303-1025.csv)
![IMG_8D59E75CCC78-1](https://user-images.githubusercontent.com/50437378/156490604-045078ae-f23b-40b7-a732-059d8060cc60.jpeg)

**Comment by priyonto** [comment]
While I was working on this part, I noticed that the data points saved and chart data points are not synchronised real time. For example, the data points are being saved let's say each 1 minute. But, if you open chart page after 1 minute the data point will not be visible there. The chart synchronised with a latency. This dissimilarities between chart points and export points is because of this in my opinion. We have a related card ( #205 ) open where the real time chart update is being discussed. 

But, what I want to be sure now is, whether this was working as expected before i.e. on the app store build. In that way I will be able to track it down if I have broken this while working. 

Thank you.

**Comment by priyonto** [comment]
@markoaamunkajo I have tested it on the app store build and the issue is reproducible on that build too. The chart is updated with a big latency after storing the data in the local database.

**Comment by markoaamunkajo** [comment]
@priyonto Yeah I think this is likely an issue that most active users will not notice but new user will be confused about. I cannot remember if this was working differently on much earlier build.

**Comment by priyonto** [comment]
@markoaamunkajo  Yes, true. The earlier builds also have this same issue. So, I believe we can handle this on the separate card we have since that is is particularly about real-time updating the charts.  That card will be moved up soon.

**Comment by markoaamunkajo** [comment]
OK moving this to done as duplicate
