### ISSUE TITLE
Discussion: Handle iOS bluetooth limitation of connecting one tag to multiple devices

### ISSUE THREAD

**Issue by priyonto** [ruuvi/com.ruuvi.station.ios#747]
iOS has a limitation in connecting one tag to multiple devices at the same time. This is currently occurring some confusion among the users when the above-mentioned scenario appears.

**Comment by laurijamsa** [comment]
In the meeting we discussed that there is a chance that firmware broadcasts one false "connectable" advertisement after already connected to a phone. And this may confuse another phone(s) that may would like to connect to the sensor as they think that a sensor is connectable even if it's not (because another phone already is connected with it). We agreed that a quick fix for this could be to wait until 2 consecutive advertisements that state the sensor to be a connectable one before trying to connect to it.

**Comment by priyonto** [comment]
@markoaamunkajo 
Would you please try to reproduce the unusual behaviors we have talked about in the meeting? I have tried to reproduce it on the current dev build (256) and suddenly everything is working as expected and no unusual behavior also faced. The only thing I noticed is even though tag is not connectable the connection section on the tag settings is visible. I believe if the tag is not connectable then this section should not be visible.
![IMG_F4DCAF2E8B60-1](https://user-images.githubusercontent.com/24395776/158573571-7e1e5a9b-6fde-4e20-b26c-857869d39bf5.jpeg)

**Comment by priyonto** [comment]
I have made some improvements and am hopeful these changes will make the user experience better.

**Comment by markoaamunkajo** [comment]
QA passed
