### ISSUE TITLE
Delay when opening sensor settings

### ISSUE THREAD

**Issue by andreevdenis** [ruuvi/com.ruuvi.station.ios#793]
I've tried version 255 and it looks like getting firmware version can be improved. I've noticed that when you open settings for the first time app tries to get fw version and user have to wait for it - I can see a full screen progress. It may be very brief delay when the tag is on the table near to you. But usually sensors located around user houses somewhere. In my case it can take up to 5 seconds to open settings for sensor in the fridge in other room and it looks like it wasn't successful to get fw version - just stopped by timeout. Also for sensors with 2.5.9 we have to wait 5 seconds every time when we want to go to settings.

I think you should open sensor settings right away in all cases and use background thread to get fw version. When background thread is finished you should update UI and show fw version or "very old".

**Comment by priyonto** [comment]
@andreevdenis Thank you for reporting it. Yes, I am aware of these cases, and I have already addressed almost everything I believe on the current build(256) pushed for the QA.  However, I will still have to check on how it's doing when the tag is far away. I could not test it with extreme cases since my apartment is not much big. But, I would appreciate it if you could check the build 0.7.7(256) when it's available and share your thoughts.

**Comment by andreevdenis** [comment]
looks like fixed in 256
