### ISSUE TITLE
Landscape chart: remove active area for zooming on date/time

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station.ios#822]
Description:

User is scrolling and zooming charts in landscape mode. If he's swiping too slowly on top of date/time area he will zoom in chart instead of moving to next/previous chart.

Let's fix it by removing active area on top of date/time so user will be able to navigate between charts when touching this area.
![IMG_8407](https://user-images.githubusercontent.com/50437378/160732182-c252e3ab-5dc4-4ca7-9024-9a3cf7d2677c.jpg)
 
 Card for Android: https://github.com/ruuvi/com.ruuvi.station/issues/654

**Comment by markoaamunkajo** [comment]
1.1.0(282) @priyonto See attached video. User is zooming in in chart in landscape mode and at some point he wants to touch the time/date area to skip to next chart but he is stuck because he is doing it too slow.

https://user-images.githubusercontent.com/50437378/163673982-af580896-1b20-498a-9d60-ecd6c564d46f.mov

**Comment by priyonto** [comment]
@markoaamunkajo Thank you for the report. Yes, I was able to reproduce it. But, I am unsure whether this can be fixed anytime soon or at all. The reason is -

When a chart for a sensor is zoomed vertically that's basically creating a scenario where one scrollView(the sensor chart) is embedded on another scrollView(the one has all three charts). And, the main scrollView does not work in that scenario because the sensor scrollView is active. It's hard to explain and this might sound complicated but we will have to keep looking to find out a solution for this.

**Comment by markoaamunkajo** [comment]
@priyonto we discussed in the meeting to postpone this task together with Android. Will move this to backlog.
There will be another card regarding redesigning the charts view.

**Comment by markoaamunkajo** [comment]
@priyonto let's improve this same way as on Android.
It seems the big problem is that when zoomed in chart on iOS I cannot fast swipe down to get to next chart.
Check how it's implemented on Android.

**Comment by markoaamunkajo** [comment]
Let's test this on iPad and see if the issue is very visible in there.

**Comment by markoaamunkajo** [comment]
On iPad this can somehow be ignored when using 2 fingers to swipe up or down in landscape chart. It works for me very reliably. But on iPhone this method is unusable. We didn't receive any user feedback regarding this, shall we close this issue @laurijamsa ?

**Comment by laurijamsa** [comment]
Yep I think we will just close and get back to this later if needed
