### ISSUE TITLE
Attempt to share : Error ...need... Gateway...

### ISSUE THREAD

**Issue by DG12** [ruuvi/com.ruuvi.station.ios#860]
A sensor that is in the cloud database, but currently not in range should be able to be shared.

![SharedNeedsGateway](https://user-images.githubusercontent.com/2365961/162582725-9080a56a-29a6-4ce1-ac54-6c06421ec52d.PNG)

**Comment by DG12** [comment]
What is the reason for prohibiting sharing after not being able to share, currently inactive, Ruuvi.

Consider scenario: sensor active for several months, now out of battery or otherwise out of range, user wants associate to view data from month ago.

**Comment by laurijamsa** [comment]
Reason for this decision originally was that if a sensor has no data in the cloud, it would be a bad user experience when someone receives a shared sensor without data. And if no data in the cloud, it would mean in most cases that owner of the sensor has no Ruuvi Gateway and he/she tries to share an offline sensor which is not . But for sure some edge cases like yours could benefit an option to share it anyways. I'm ok to reopen this so that we can consider this again and decide which one is better option; restrict the sharing or not.

**Comment by laurijamsa** [comment]
I encountered the same issue myself now on Android and WebUI when tried to share my sensor that has been months nearby a Gateway but it's not nearby a Gateway right now (Gateway has been offline 6 days). Would be probably better to allow sharing in these kinds of cases. But the question is, that how do we differentiate these cases from cases where user never had a Gateway nearby the sensor. Or do we even need to? Bluetooth sensor users without Ruuvi Gateways would start to share their sensors to their friends and then sharees would see no data -> bad new user experience. Should we start to store data to the cloud from the app itself at some point - this is a bigger topic to discuss about internally with our team.

I see the same error message on all clients ios/android/webui. This means that we'd need to remove this sharing restriction on all the clients if we'd like to proceed with this. Before rushing to modify this behaviour, we need to understand what kinds of problems it would cause. Comments are welcomed.

**Comment by laurijamsa** [comment]
Opened a feature request topic and closing this issue. 

https://f.ruuvi.com/t/sharing-a-sensor-that-hasnt-recently-been-nearby-a-ruuvi-gateway/5858
