### ISSUE TITLE
Add instructions for verifying build

### ISSUE THREAD

**Issue by ojousima** [ruuvi/com.ruuvi.station.ios#879]
Users should be able to check their app .apk against automated builds, similar to https://core.telegram.org/reproducible-builds

**Comment by priyonto** [comment]
@ojousima I think this is not feasible for iOS since iOS doesn't produce apk like builds which can be installed on any iOS device. The only mode of distribution is through Apple's distribution system. Telegram docs mentioned It requires a jailbroken device to verify the builds which is probably not what we want to promote either.

**Comment by markoaamunkajo** [comment]
Closing this card as it's not necessary atm
