### ISSUE TITLE
Make it possible to configure how accurately measurements are shown on the sensor card

### ISSUE THREAD

**Issue by laurijamsa** [ruuvi/com.ruuvi.station.ios#935]
Often it's not important to know temperature, humidity and air pressure in 0.01 decimal resolution and we should allow users to decide if they would like to see the measurements in the live sensor card (and dashboard) in 0.01, 0.1 or 1 accuracy.

Make a new global app setting, a similar selection that temp/humi/pressure units currently have. Round the values like we normally do in the app (0.45 -> 0.5, 0,44 -> 0,4). Localise the decimal pointer ./, according user's language setting. Sync this setting to the cloud.

**Measurement Resolution**
======================

(*) 0.01
( ) 0.1
( ) 1

Select how accurately you'd like to see sensors' live measurement values in the app. This setting doesn't affect history graphs or alerts.

Android issue: https://github.com/ruuvi/com.ruuvi.station/issues/697

**Comment by markoaamunkajo** [comment]
Waiting for Android build to compare as agreed in meeting

**Comment by markoaamunkajo** [comment]
@priyonto some fixes for iOS on this:

1. Please don't let the resolution affect following:

CSV export resolution
Offset correction resolution

2. It seemed that resolution wouldn't sync over cloud for me in my testing session.

**Comment by markoaamunkajo** [comment]
@priyonto please use word "charts" instead of "graphs". We have unified this in between apps previously, same fix is being made for Android.
![charts_not_graphs_ios](https://user-images.githubusercontent.com/50437378/180918273-85ad500f-7b2e-4909-aff4-200df95dc520.jpg)

**Comment by markoaamunkajo** [comment]
QA passed

**Comment by markoaamunkajo** [comment]
1.3(312)

Actually looks like humidity calculation is using temperature resolution value and it's incorrect, because humidity cannot then show more resolution.

Expected: Calculate from full resolution and only hide decimals and do rounding accordingly.

![photo_2022-07-29 16 57 00](https://user-images.githubusercontent.com/50437378/181734898-7fae9b2d-7d69-4c30-835d-3fc1eba4401b.jpeg)
![photo_2022-07-29 16 56 58](https://user-images.githubusercontent.com/50437378/181734904-f9b5aabf-4f29-41b7-b876-85d1b3b3b843.jpeg)
![photo_2022-07-29 16 56 55](https://user-images.githubusercontent.com/50437378/181734907-35fc6c51-c5f6-404b-b165-ef76d9e97179.jpeg)

**Comment by markoaamunkajo** [comment]
Looks like this also affects widgets. Resolution is missing 1 decimal for same, because that was the selected resolution.
![photo_2022-07-29 17 07 31](https://user-images.githubusercontent.com/50437378/181736908-3393cfac-5060-424c-807d-8e61cbd93cb4.jpeg)

**Comment by markoaamunkajo** [comment]
QA passed
